### ISSUE TITLE
Get api data rendering on page (good first issue)

### ISSUE THREAD

**Issue by anneloes94** [mikaalnaik/Toronto-Beach-App#2]
A first step can be to simply get the beach data to show up on the home page. 
1. Fork & clone repo
2. Do an npm install
3. Make a call to the [TorontoBeach api](https://github.com/mikaalnaik/TorontoBeach) in pages/index.js
4. Get the data to show up :)

**Comment by mikaalnaik** [comment]
@anneloes94 this is resolved as of June 19th, 2020 on commit
`a9db7c7e86547a360cb8470608d072c1485e711b`
